server:
  servlet:
    context-path: /

# better readable jackson serialization format
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

#   maria db
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://34.64.196.39:3306/video-manage?characterEncoding=UTF-8&serverTimezone=UTC;MVCC=TRUE
    username: root
    password: 1234

  devtools:
    restart:
      enabled: true

# 로컬 디비 테스트 용도
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#  h2:
#    console:
#      enabled: true
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:


  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  #  base64-secret : mySecret
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-refresh: 108000
  route:
    authentication:
      path: /auth
      refresh: /refresh

logging:
  level:
    org.zerhusen.security: DEBUG
#    org.springframework.security: DEBUG
file:
  dir: C:/upload/